# Generated by Django 2.0.6 on 2021-09-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('pk_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_y_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['fecha_y_hora'],
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('pk_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('Dpi', models.BigIntegerField()),
                ('Edad', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('pk_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=200)),
                ('edad', models.BigIntegerField()),
                ('vacunas', models.BigIntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpractica.cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpractica.mascota'),
        ),
    ]
